train_data:
  dataset_name: "MNISTDataset"
  num_samples: 60_000
  split: "train"
  torch_transform: null
  seed: 42
  negative_label: False

optim:
  batch_size: 4096
  num_epochs: 100
  weight_decay: 1e-4
  betas: [0.9, 0.999]

scale:
  model_to_scale: "/home/nsa325/work/nnscaling/model_saves/mnist_model.safetensors"
  scale_location: 2
  num_scaled_layers: 5
  scale_style: "replace" # "prepend" or "replace"
  learning_rate: 5e-3
  scale_nonlinearity: "relu"
  lambda_reconstruction: 0
  lambda_prediction: 1
  
autoencoder:
  ae_dim: 128
  learning_rate: 1e-3
  ae_nonlinearity: "leakyrelu"
  lambda_reconstruction: 5
  lambda_prediction: 1
  train_fraction: 1.0
  reuse_file: null
  # reuse_file: "/home/nsa325/work/nnscaling/model_saves/scaling/loc_1_autoencoder_mnist_model.safetensors"

seed: 42
save_name: "mnist_model"
save_dir: "/home/nsa325/work/nnscaling/model_saves/scaling/"
print_freq: 5
