[tool.poetry]
name = "nnscaling"
version = "0.1.0"
description = ""
authors = ["Nishant Aswani <nsa325@nyu.edu>"]
readme = "README.md"
package-mode = true

[tool.poetry.dependencies]
python = "^3.10"
torch = { version = "2.1.0", source = "pytorch" }
torchvision = { version = "*", source = "pytorch" }
numpy = "~1.26"
ipykernel = "^6.29.5"
fire = "^0.7.0"
safetensors = "^0.4.5"
rich = "^13.9.3"
torchinfo = "^1.8.0"
jaxtyping = "^0.2.34"
pydantic = "^2.9.2"
torcheval = "^0.0.7"
pyyaml = "^6.0.2"
tqdm = "^4.66.5"
wandb = "^0.18.5"
python-dotenv = "^1.0.1"


[[tool.poetry.source]]
name = "pytorch"
url = "https://download.pytorch.org/whl/cu121"
priority = "explicit"

[tool.poetry.group.test.dependencies]  
pytest-randomly = "^3.15.0"  
pytest = "^8.3.3"  
  
[tool.poetry.group.dev.dependencies]  
ruff = "^0.4.10"  
ipykernel = "^6.29.5"
matplotlib="*"
seaborn="*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
testpaths = [
    "tests",
]

[tool.ruff.lint]
ignore = ["F722"]
unfixable = ["F401"]