seed: 21
batch_size: 4_096
num_epochs: 50

learning_rate: 5e-3
weight_decay: 0
lambda_complexity: 0
lambda_uniformity: 0
out_features: 10
betas: [0.9, 0.999]

model_to_scale: "/home/nsa325/work/nnscaling/model_saves/fashion_model.safetensors"
scale_location: 1
num_scaled_layers: 2
scale_nonlinearity: "relu"
scale_style: "replace" # "prepend" or "replace"

train_data: 
    dataset_name: "FashionMNISTDataset"
    num_samples: 1
    split: "train"
    torch_transform: null
    seed: 42
    negative_label: False
    
save_name: "fashion_model"
save_dir: "/home/nsa325/work/nnscaling/model_saves/scaling/"
print_freq: 3