entity: nishantaswani
project: scaling
name: train_sweep

method: grid
metric:
  name: train_loss
  goal: minimize

num_sweeps: 500

parameters:
  batch_size:
    value: 1_000
  learning_rate:
    values: [5e-3, 1e-2]
  weight_decay:
    value: 0
  lambda_complexity:
    values: [0, 1e-6, 1e-4, 1e-2]
  lambda_uniformity:
    values: [0, 1e-6, 1e-4, 1e-2]
  beta_one:
    values: [9e-1, 8e-1]
  beta_two:
    values: [9.99e-1, 9e-1]
  num_epochs: 
    value: 1_000
  seed:
    values: [42, 21, 96]
  out_features: 
    value: 2
  model_to_scale: 
    value: "/home/nsa325/work/nnscaling/model_saves/lotusroot_model.safetensors"
  scale_location:
    value: 1
  num_scaled_layers: 
    value: 20
  train_data: 
      parameters:
        num_samples: 
          value: 5_000
        split: 
          value: train
        torch_transform:
          value: null
        seed:
          value: 42
        negative_label:
          value: false
        dataset_name: 
          value: "LotusRootDataset"