seed: 0
batch_size: 1_000
num_epochs: 5_000

learning_rate: 5e-3
weight_decay: 1e-2
out_features: 2
hidden_neurons: [8,6,4,3]

train_data: 
    dataset_name: "YinYangNoDotsBinaryDataset"
    num_samples: 3_000
    split: "train"
    torch_transform: null
    seed: 42
    negative_label: false

save_name: "yinyang_model"
save_dir: "/home/nsa325/work/nnscaling/model_saves/"
print_freq: 500