seed: 0
batch_size: 1_000
num_epochs: 5_000

learning_rate: 0.005
weight_decay: 1e-2
out_features: 2
hidden_neurons: [8,6,4,3]

train_data: 
    num_samples: 2_000
    split: "train"
    torch_transform: null
    seed: 42
    negative_label: false

save_dir: "/home/nsa325/work/nnscaling/model_saves/"
print_freq: 500